### PR TITLE
Connect to localhost server dialog

### PR DESCRIPTION
**Pull request by ComicSAS**
### Description
Via [issue](https://github.com/ShiftHackZ/Stable-Diffusion-Android/issues/202)

- Implemented connect to localhost with ssh-tunneling warning dialog
- Updated README.md

### Video

https://github.com/user-attachments/assets/20d77f67-a9c1-4ce0-ab0d-beac1398b4ae

### Checklist
- [x] I have ensured this PR does not contain any breaking changes for existing functionality;
- [ ] I have added automated tests that cover the new behavior and removed obsolete tests and code;

### Tested On
- [x] Real device
[Xiaomi 11T Pro](https://www.gsmarena.com/xiaomi_11t_pro-11100.php) with Android 14

P.S. Feature requires testing via localhost(127.0.0.1) with ssh-tunneling enabled.

### CODE REVIEW

**Review by ShiftHackZ — CHANGES_REQUESTED** [review]
@ComicSAS Can not build from your upstream branch. Seems like string resource `yes_i_did` is missing in string resources.

image

**Comment by ComicSAS** [comment]
> @ComicSAS Can not build from your upstream branch. Seems like string resource `yes_i_did` is missing in string resources.
> 
> image

**Comment by ComicSAS** [comment]
> @ComicSAS Can not build from your upstream branch. Seems like string resource `yes_i_did` is missing in string resources.
> 
> image

Fixed.

**Review by ShiftHackZ — APPROVED** [review]
Looks good, verified that it works with Termux SSH tunnel.

**Pull request merged**
